charts/kubernetes/templates/_helpers.tpl, charts/kubernetes/templates/scraper.yaml, charts/kubernetes/templates/topology.yaml, charts/kubernetes/values.yaml
Fixes: #21
Fixes: #22 
Fixes: #23
=> chore: kubernetes topology - group by namespace

charts/aws/.helmignore, charts/aws/Chart.yaml, charts/aws/templates/NOTES.txt, charts/aws/templates/_helpers.tpl, charts/aws/templates/aws.yaml, charts/aws/values.yaml
Closes: https://github.com/flanksource/mission-control-registry/issues/24
=> feat: add aws scraper

charts/mission-control/templates/mission-control.yaml, charts/mission-control/values.yaml
=> chore: add isAgent flag

charts/kubernetes/Chart.yaml, charts/kubernetes/templates/scraper.yaml, charts/kubernetes/templates/topology.yaml, charts/kubernetes/values.yaml, charts/prometheus/Chart.yaml, charts/prometheus/templates/prometheus.yaml, charts/prometheus/values.yaml
=> chore: add prometheus url option for kubernetes and prometheus chart

charts/kubernetes/values.yaml
@adityathebe Make sure to update the registry when breaking API changes are made
=> chore: update default event exclusion values in k8s scraper

.editorconfig, charts/kubernetes/values.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/54
=> chore: exclude verbose changes in kubernetes

charts/azure/templates/azure.yaml, charts/azure/values.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/51
merge after: https://github.com/flanksource/config-db/pull/418
=> feat: add relationship config to link aks resources with k8s resources

charts/kubernetes/Chart.yaml, charts/kubernetes/values.yaml
Depends on https://github.com/flanksource/config-db/pull/426/files
=> chore: add git repo relationship in k8s scraper

topologies/flux/flux.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/62
=> fix: status for HelmRelease & Kustomization

topologies/flux/flux.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/61
=> fix: flux controllers

charts/flux/templates/flux.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/63
=> fix: flux topology

charts/flux/Chart.yaml, charts/flux/templates/flux.yaml
=> chore: move flux git to cel

charts/mission-control/templates/mission-control.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/73
=> feat: link mission-control postgres component to the postgres pod

charts/mission-control/templates/mission-control.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/15
=> fix and update mission control watchtower

charts/flux/Chart.yaml, charts/flux/templates/flux.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/97
Depends on: https://github.com/flanksource/canary-checker/pull/1751
=> chore: use catalog check for flux

charts/aws/values.yaml, charts/azure/values.yaml, charts/mission-control/templates/mission-control.yaml, charts/mission-control/templates/playbooks.yaml, charts/mission-control/values.yaml
update relationship selectors in azure & aws charts
=> feat: use the latest connection string format & remove hardcoded ones

charts/kubernetes/Chart.yaml, charts/kubernetes/templates/topology.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/98
=> chore: use direct properties for pod/node

charts/mission-control/templates/mission-control.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/112
=> chore: use labels instead of tags

charts/argocd/Chart.yaml, charts/argocd/templates/argocd.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/101
=> feat(argo topology): create child components for all resources

.github/workflows/test.yml, Makefile, charts/argocd/Chart.yaml, charts/aws/Chart.yaml, charts/aws/values.yaml, charts/azure/Chart.yaml, charts/flux/Chart.yaml, charts/kubernetes/Chart.yaml, charts/mission-control/Chart.yaml, charts/prometheus/Chart.yaml, charts/prometheus/values.yaml, test_charts.sh
Fixes: https://github.com/flanksource/mission-control-registry/issues/109
=> chore: add templating test for chart

charts/kubernetes/Chart.yaml, charts/kubernetes/templates/playbooks/playbooks.yaml, charts/kubernetes/values.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/140
=> feat: add delete pod playbook

charts/aws/Chart.yaml, charts/aws/values.yaml
=> chore: ignore network attach/detach events in aws

charts/mission-control/Chart.yaml, charts/mission-control/templates/mission-control.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/180
=> fix: job component in mission control topology

charts/aws/Chart.yaml, charts/aws/templates/topology.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/179
=> fix: missing key handle in aws topology

charts/kubernetes/Chart.yaml, charts/kubernetes/templates/_helpers.tpl, test_charts.sh
Fixes: https://github.com/flanksource/mission-control-registry/issues/195
=> fix: add foreach for namespace pod metrics

charts/flux/templates/flux.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/198
=> feat: flux topology group by cluster tag

charts/kubernetes/Chart.yaml, charts/kubernetes/templates/_helpers.tpl, charts/kubernetes/templates/topology.yaml, test_charts.sh
Fixes: https://github.com/flanksource/mission-control-registry/issues/202
=> fix: rendering error with kubeconfig in k8s chart

charts/flux/templates/playbooks/helm-update-chart-version.yaml, charts/flux/templates/playbooks/helm-update-values.yaml, charts/flux/templates/playbooks/reconcile.yaml, charts/flux/templates/playbooks/resume.yaml, charts/flux/templates/playbooks/suspend.yaml, charts/flux/values.yaml, charts/kubernetes/README.md, charts/kubernetes/templates/playbooks/create-deployment.yaml, charts/kubernetes/templates/playbooks/update-resource-image.yaml, charts/kubernetes/templates/playbooks/update-resource-resources.yaml, charts/kubernetes/values.yaml
=> chore: add k8s playbooks for deploying, updating image and request/limits

charts/kubernetes/templates/topology.yaml
- Need to inject groupBy value into config and component selectors in additiont o lookups.catalog
=> fix: multiple clusters per agent

charts/kubernetes/values.yaml
resolves: https://github.com/flanksource/config-db/issues/767
=> fix(kubernetes): default exclusions

charts/kubernetes/templates/_helpers.tpl, charts/kubernetes/values.schema.json, charts/kubernetes/values.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/188
=> chore: add gke metrics for k8s

charts/kubernetes/templates/playbooks/kubectl-logs.yaml
Github diff seems to be breaking, actual diff: https://www.diffchecker.com/pvYZxpP8/
=> fix: kubernetes log playbook

charts/mission-control/templates/_helpers.tpl, charts/mission-control/templates/mission-control.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/254
=> chore: handle agent specific bugs in watchtower

charts/kubernetes/templates/topology.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/244
=> chore: add defaults for pod max memory and cpu

charts/kubernetes/values.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/275
=> chore: mask connection's sensitive values

charts/playbooks-flux/values.yaml
@moshloop I think default should always be true, direct commits to main branch should be intentional
=> chore(playbooks-flux): set create pull request to true by default

charts/kubernetes/values.yaml
=> chore(kubernetes): classify pod restart and ignore all info for cronjob pods

.github/workflows/release.yml, .github/workflows/stable-release.yml
Fixes: https://github.com/flanksource/mission-control-registry/issues/319
=> feat: add support for beta and stable release

charts/kubernetes/values.schema.json, charts/kubernetes/values.yaml, test_charts.sh
Fixes: https://github.com/flanksource/mission-control-registry/issues/340
=> chore(kubernetes): force user to enter cluster name

.gitignore, charts/helm/.helmignore, charts/helm/.yamllint, charts/helm/Chart.yaml, charts/helm/Makefile, charts/helm/templates/_helpers.tpl, charts/helm/templates/playbook.yaml, charts/helm/templates/scraper.yaml, charts/helm/values.schema.json, charts/helm/values.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/322
=> feat: helm scraper chart

charts/kubernetes/templates/_helpers.tpl, charts/kubernetes/values.schema.json, charts/kubernetes/values.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/237
=> feat: add support for cluster max cpu and memory

charts/mission-control/templates/mission-control.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/353
=> chore(mission-control): add cpu/memory property in component cards

charts/playbooks-kubernetes/templates/cleanup-failed-pods.yaml, charts/playbooks-kubernetes/templates/create-deployment.yaml, charts/playbooks-kubernetes/templates/delete.yaml, charts/playbooks-kubernetes/templates/deploy-helm-chart.yaml, charts/playbooks-kubernetes/templates/ignore.yaml, charts/playbooks-kubernetes/templates/kubectl-logs.yaml, charts/playbooks-kubernetes/templates/pod-snapshot.yaml, charts/playbooks-kubernetes/templates/request-namespace-access.yaml, charts/playbooks-kubernetes/templates/restart.yaml, charts/playbooks-kubernetes/templates/scale.yaml, charts/playbooks-kubernetes/templates/update-image.yaml, charts/playbooks-kubernetes/templates/update-resource.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/372
=> feat(kubernetes-playbooks): use kubeconfig from scraper

charts/playbooks-kubernetes/Makefile, charts/playbooks-kubernetes/README.md, charts/playbooks-kubernetes/templates/_helpers.tpl, charts/playbooks-kubernetes/templates/cleanup-failed-pods.yaml, charts/playbooks-kubernetes/templates/create-deployment.yaml, charts/playbooks-kubernetes/templates/delete.yaml, charts/playbooks-kubernetes/templates/deploy-helm-chart.yaml, charts/playbooks-kubernetes/templates/ignore.yaml, charts/playbooks-kubernetes/templates/kubectl-logs.yaml, charts/playbooks-kubernetes/templates/pod-snapshot.yaml, charts/playbooks-kubernetes/templates/request-namespace-access.yaml, charts/playbooks-kubernetes/templates/restart.yaml, charts/playbooks-kubernetes/templates/scale.yaml, charts/playbooks-kubernetes/templates/update-image.yaml, charts/playbooks-kubernetes/templates/update-resource.yaml, charts/playbooks-kubernetes/values.schema.json, charts/playbooks-kubernetes/values.yaml
=> feat: add option to enable podIdentity and serviceAccount access to

charts/playbooks-ai/README.md, charts/playbooks-ai/templates/diagnose-resource.yaml, charts/playbooks-ai/templates/diagnose-slack-notification.yaml, charts/playbooks-ai/templates/notification.yaml, charts/playbooks-ai/templates/recommend-playbooks.yaml, charts/playbooks-ai/values.schema.json, charts/playbooks-ai/values.yaml
* improve existing AI playbooks
=> feat: add new playbook that recommends playbook with AI

charts/kubernetes/Makefile, charts/kubernetes/README.md, charts/kubernetes/ci/kubeconfig-values.yaml, charts/kubernetes/templates/_helpers.tpl, charts/kubernetes/templates/scraper.yaml, charts/kubernetes/templates/topology.yaml, charts/kubernetes/values.schema.json, charts/kubernetes/values.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/403
=> feat(kubernetes): support for new connection types

charts/kubernetes/values.schema.json, charts/kubernetes/values.yaml
Fixes: https://github.com/flanksource/config-db/issues/1457
=> fix(kubernetes): keep default connection options as null

charts/mission-control/templates/mission-control.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/387
=> feat(mission-control-watchtower): add health check for scraper

charts/kubernetes-view/templates/cluster-overview.yaml, charts/kubernetes-view/templates/pods.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/449
=> fix: pods view

charts/kubernetes-view/templates/pod.yaml, charts/kubernetes-view/values.schema.json, charts/kubernetes-view/values.yaml
resolves: https://github.com/flanksource/mission-control-registry/issues/450
=> feat(kubernetes-view): pod view

charts/mission-control/templates/playbooks.yaml
Fixes: https://github.com/flanksource/mission-control-registry/issues/446
=> chore(mission-control): add playbook for vacuum
